select 
    payer_id as "Пользователь",
    i.id as "Номер ордера",
    c."name" as "Клиент",
    cl.system_name as "Валюта",
    isl.system_name as "Статус",
    i.amount as "Сумма",
    (i.engine_id IS NOT NULL) AS "Выданы реквизиты",
    i.created_at as "Дата создания",
    'payin' as "Тип ордера",
    CASE
        WHEN i.status_id <> 2 THEN
        CASE
            WHEN i.error_code = 101 THEN 'Rejected by client blacklist rule'
            WHEN i.error_code = 102 THEN 'From merchant ID block'
            WHEN i.error_code = 103 THEN 'Suspicious LLC country'
            WHEN i.error_code = 104 THEN 'Suspicious provider'
            WHEN i.error_code = 105 THEN 'Suspicious subnet'
            WHEN i.error_code = 107 THEN 'Blacklist API'
            WHEN i.error_code = 108 THEN 'Blacklist Form'
            WHEN i.error_code = 109 THEN 'Limit exceeded'
            WHEN i.error_code = 111 THEN 'Bad user agent'
            WHEN i.error_code = 112 THEN 'Primary traffic blocked'
            WHEN i.error_code = 114 THEN 'Card blocked'
            WHEN i.error_code = 115 THEN 'Canceled by peer'

            WHEN i.error_code = 2000 THEN 'Cannot accept default terminal ID'
            WHEN i.error_code = 2002 THEN 'Another terminal ID was used'
            WHEN i.error_code = 2003 THEN 'Not supported currency'
            WHEN i.error_code = 2004 THEN 'Not supported payment system'
            WHEN i.error_code = 2007 THEN 'Not supported bank'
            WHEN i.error_code = 2010 THEN 'Invalid order status'
            WHEN i.error_code = 2033 THEN 'Method ID validation failed'
            WHEN i.error_code = 2034 THEN 'Merchant URL validation failed'
            WHEN i.error_code = 2037 THEN 'Can refund only H2H'
            WHEN i.error_code = 2038 THEN 'Order is already refunded'
            WHEN i.error_code = 2041 THEN 'Refund timeout exceeded'
            WHEN i.error_code = 2042 THEN 'Engine not set'
            WHEN i.error_code = 2044 THEN 'Engine order ID not set'
            WHEN i.error_code = 2045 THEN 'Balance validation fail'
            WHEN i.error_code = 2048 THEN 'Can chargeback only H2H'
            WHEN i.error_code = 2049 THEN 'Can not change success refund'
            WHEN i.error_code = 3001 THEN 'Blocked by limit'
            WHEN i.error_code = 3002 THEN 'Unknown external error'
            WHEN i.error_code = 3007 THEN '3DS PARes status not Y'
            WHEN i.error_code = 3008 THEN '3DS VERes status U'
            WHEN i.error_code = 3009 THEN '3DS decline in VERes'
            WHEN i.error_code = 3010 THEN 'No attempts left'
            WHEN i.error_code = 3011 THEN 'Session time limit'
            WHEN i.error_code = 3013 THEN 'TDS signature test failed'
            WHEN i.error_code = 3016 THEN 'Fraud do not honour'
            WHEN i.error_code = 3017 THEN 'Original transaction not found'
            WHEN i.error_code = 3018 THEN 'Card limits exceeded'
            WHEN i.error_code = 3019 THEN 'Wrong expiry date'
            WHEN i.error_code = 3025 THEN 'Security violation'
            WHEN i.error_code = 3026 THEN 'Transaction not permitted'
            WHEN i.error_code = 3031 THEN 'Cannot contact bank'
            WHEN i.error_code = 3032 THEN 'Invalid operation'
            WHEN i.error_code = 3033 THEN 'SSL forbidden'
            WHEN i.error_code = 3036 THEN 'Refund more than deposited'
            WHEN i.error_code = 3037 THEN '3DS rule error'
            WHEN i.error_code = 3038 THEN 'Terminal select rule error'
            WHEN i.error_code = 3039 THEN 'General external error'
            WHEN i.error_code = 3040 THEN '3DS declined in ARes'
            WHEN i.error_code = 3042 THEN '3DS authentication cancelled'
            WHEN i.error_code = 3043 THEN '3DS authentication failed'
            WHEN i.error_code = 3044 THEN '3DS unknown RReq status'
            WHEN i.error_code = 3045 THEN '3DS erroneous challenge'
            WHEN i.error_code = 3047 THEN 'Postal address verification failed'
            WHEN i.error_code = 3052 THEN 'Duplicate order'
            WHEN i.error_code = 3057 THEN 'Invalid CVV2'
            WHEN i.error_code = 3058 THEN 'Invalid AVS'
            WHEN i.error_code = 3061 THEN 'Currency mismatch'
            WHEN i.error_code = 3062 THEN 'Authorization expired'
            WHEN i.error_code = 3063 THEN 'Reversal needed'
            WHEN i.error_code = 3064 THEN 'Invalid transaction type'
            WHEN i.error_code = 3065 THEN 'Batch not found'
            WHEN i.error_code = 3066 THEN 'Settlement failed'
            WHEN i.error_code = 3067 THEN 'Capture amount exceeded'
            WHEN i.error_code = 3069 THEN 'Currency not accepted'
            WHEN i.error_code = 3070 THEN 'Card scheme restriction'
            WHEN i.error_code = 3071 THEN 'Merchant category restriction'
            WHEN i.error_code = 3075 THEN 'Recurring cancelled'
            WHEN i.error_code = 3076 THEN 'Recurring expired'
            WHEN i.error_code = 3077 THEN 'Recurring not found'
            WHEN i.error_code = 3079 THEN 'Velocity check failed'
            WHEN i.error_code = 3083 THEN 'Invalid token'
            WHEN i.error_code = 3085 THEN 'Account verification needed'
            WHEN i.error_code = 3087 THEN 'Risk check failed'
            WHEN i.error_code = 3088 THEN 'PCI compliance failure'
            WHEN i.error_code = 3101 THEN 'Invalid billing descriptor'
            WHEN i.error_code = 3102 THEN 'Dynamic currency conversion failed'
            WHEN i.error_code = 3104 THEN 'Currency conversion expired'
            WHEN i.error_code = 3105 THEN 'Cross-border declined'
            WHEN i.error_code = 3108 THEN 'Mandate required'
            WHEN i.error_code = 3109 THEN 'Mandate invalid'
            WHEN i.error_code = 3110 THEN 'Direct debit failed'
            WHEN i.error_code = 3111 THEN 'Chargeback dispute lost'
            WHEN i.error_code = 3112 THEN 'Fraud investigation'
            WHEN i.error_code = 3114 THEN 'Account temporarily locked'
            WHEN i.error_code = 3117 THEN 'Payment method invalid'
            WHEN i.error_code = 3118 THEN 'Merchant account disabled'

            WHEN i.error_code IN (2013, 3091) THEN 'Client Amount Below Limit'
            WHEN i.error_code IN (2014, 3092) THEN 'Client Amount Over Limit'
            WHEN i.error_code IN (2015, 3093) THEN 'Client Turnover Below Limit'
            WHEN i.error_code IN (2016, 3094) THEN 'Client Turnover Over Limit'
            WHEN i.error_code IN (2019, 3097) THEN 'Engine Amount Below Limit'
            WHEN i.error_code IN (2020, 3098) THEN 'Engine Amount Over Limit'
            WHEN i.error_code IN (2021, 3099) THEN 'Engine Turnover Below Limit'
            WHEN i.error_code IN (2022, 3100) THEN 'Engine Turnover Over Limit'
            WHEN i.error_code = 2047 THEN 'Cannot chargeback unsuccessful order'
            WHEN i.error_code = 3035 THEN '3DS rule failed'
            WHEN i.error_code = 3089 THEN 'Card validation error'
            WHEN i.error_code = 2012 THEN 'Payment form already generated'
            WHEN i.error_code = 3107 THEN 'This feature is coming soon, just wait for it'
            WHEN i.error_code = 2035 THEN 'Invalid phone number'
            WHEN i.error_code = 106 THEN 'Rejected by anti-fraud rule'
            WHEN i.error_code = 3015 THEN 'Invalid merchant'
            WHEN i.error_code = 3020 THEN 'Contact issuer'
            WHEN i.error_code = 3051 THEN 'Try again later'
            WHEN i.error_code = 3055 THEN 'CVV2 failure'
            WHEN i.error_code = 3091 THEN 'Amount is below limit'
            WHEN i.error_code = 2032 THEN 'Payment system validation failed'
            WHEN i.error_code = 2036 THEN 'Fail on engine action'
            WHEN i.error_code = 3023 THEN 'Wrong PAN'
            WHEN i.error_code = 2014 THEN 'Amount is over limit'
            WHEN i.error_code = 4001 THEN 'Bank validation failed'

            WHEN i.error_code = 113 THEN 'Requisites are broken'
            WHEN i.error_code = 1001 THEN 'Internal error'
            WHEN i.error_code = 1003 THEN 'Internal error'
            WHEN i.error_code = 2027 THEN 'IP validation failed'
            WHEN i.error_code = 3103 THEN 'Card number validation failed'
            WHEN i.error_code = 1000 THEN 'Internal error'
            WHEN i.error_code = 2001 THEN 'Terminal ID credentials not found'
            WHEN i.error_code = 3003 THEN 'SSL error'
            WHEN i.error_code = 3056 THEN 'Transaction not permitted to cardholder'
            WHEN i.error_code = 3074 THEN '3Dv2 failed'
            WHEN i.error_code = 2016 THEN 'Turnover is over limit'
            WHEN i.error_code = 3096 THEN 'BIN validator failed'
            WHEN i.error_code = 3113 THEN 'Invalid phone number'
            WHEN i.error_code = 3120 THEN 'Bad request. Check your credentials'
            WHEN i.error_code = 3121 THEN 'Card declined by payment system'
            WHEN i.error_code = 3005 THEN '3DS v1 authentication is not possible. Declined by iReq in PARes'
            WHEN i.error_code = 3024 THEN 'Not enough funds'
            WHEN i.error_code = 3073 THEN '3DS additional authentication required'
            WHEN i.error_code = 3081 THEN 'Card not registered for 3DS'
            WHEN i.error_code = 2017 THEN 'PAN validator failed'
            WHEN i.error_code = 2029 THEN 'This feature is coming soon, just wait for it'
            WHEN i.error_code = 3006 THEN '3DS v1 authentication is not possible. Declined. DS connection timeout'
            WHEN i.error_code = 3014 THEN 'TDS impossible'
            WHEN i.error_code = 3028 THEN 'Invalid card number'
            WHEN i.error_code = 3046 THEN '3DS authentication. ACS cancelled challenge by timeout'
            WHEN i.error_code = 3053 THEN 'Payer country is forbidden'
            WHEN i.error_code = 3090 THEN 'Payment form already generated'
            WHEN i.error_code = 2018 THEN 'BIN validator failed'
            WHEN i.error_code = 2031 THEN 'Bank validation failed'
            WHEN i.error_code = 3122 THEN 'Invalid amount or currency'
            WHEN i.error_code = 2039 THEN 'Cannot refund unsuccessful order'
            WHEN i.error_code = 3012 THEN '3DS authentication is not possible'
            WHEN i.error_code = 3041 THEN '3DS authentication status in ARes is unknown'
            WHEN i.error_code = 3086 THEN 'Cannot get order by UID'
            WHEN i.error_code = 2022 THEN 'Turnover is over limit'
            WHEN i.error_code = 2046 THEN 'Order is already chargebacked'
            WHEN i.error_code = 3060 THEN 'Non-3DS operation is not allowed'
            WHEN i.error_code = 3072 THEN 'Cannot find gate for card'
            WHEN i.error_code = 3095 THEN 'PAN validator failed'
            WHEN i.error_code = 2025 THEN 'Card number validation failed'

            WHEN i.error_code = 101 THEN 'Rejected by anti-fraud rule'
            WHEN i.error_code = 110 THEN 'Requests limit exceeded. User has been blacklisted'
            WHEN i.error_code = 3080 THEN '3DS declined'
            WHEN i.error_code = 2008 THEN 'Cannot get order by UID'
            WHEN i.error_code = 3093 THEN 'Turnover is below limit'
            WHEN i.error_code = 2024 THEN 'BIN validator failed'
            WHEN i.error_code = 103 THEN 'Suspicious request'
            WHEN i.error_code = 2050 THEN 'Cannot update chargeback to new status'
            WHEN i.error_code = 3021 THEN 'Wrong merchant ID/terminal ID'
            WHEN i.error_code = 3029 THEN 'Reenter transaction'
            WHEN i.error_code = 3082 THEN 'Transaction expired'
            WHEN i.error_code = 2006 THEN 'Insufficient funds'
            WHEN i.error_code = 3034 THEN 'SSL without CVC forbidden'
            WHEN i.error_code = 2028 THEN 'Not configured for you, please contact the manager'
            WHEN i.error_code = 3106 THEN 'Not configured for you, please contact the manager'
            WHEN i.error_code = 3119 THEN 'Not found. Check your credentials'
            WHEN i.error_code = 2043 THEN 'Engine not available'
            WHEN i.error_code = 3030 THEN 'Invalid message format'
            WHEN i.error_code = 3078 THEN 'Payment rejected'
            WHEN i.error_code = 3084 THEN 'Transaction timed out'
            WHEN i.error_code = 3092 THEN 'Amount is over limit'
            WHEN i.error_code = 3097 THEN 'Amount is below limit'
            WHEN i.error_code = 3115 THEN 'Contact support'
            WHEN i.error_code = 3048 THEN 'General payment system error'
            WHEN i.error_code = 3054 THEN '3DS timeout'
            WHEN i.error_code = 3059 THEN 'Card not active'
            WHEN i.error_code = 3068 THEN 'Transaction not allowed at terminal'
            WHEN i.error_code = 2030 THEN 'Geo validation failed'
            WHEN i.error_code = 3116 THEN 'Cardholder name not specified'
            WHEN i.error_code = 4000 THEN 'Geo validation failed'
            WHEN i.error_code = 1002 THEN 'Internal error'
            WHEN i.error_code = 2005 THEN 'No available engines'
            WHEN i.error_code = 2040 THEN 'Order is already on refund'

            WHEN fail_cause LIKE '%temporarily blocked for%' THEN 'Temporarily blocked for exceeded spam'
            WHEN fail_cause LIKE '%requests limit exceeded%' THEN 'Requests limit exceeded'
            WHEN fail_cause LIKE '%requests limit exceeded hardly%' THEN 'Requests limit exceeded hardly. User has been added to black-list'
            WHEN fail_cause LIKE '%temporarily blocked for exceeded card spam%' THEN 'Temporarily blocked for exceeded card spam filter limits '
            WHEN fail_cause LIKE '%ip is in API blacklist%' THEN 'IP is in API Blacklist'
            WHEN fail_cause LIKE '%suspicious request%' THEN 'Suspicious Request'
            WHEN fail_cause LIKE '%primary traffic blocked%' THEN 'Primary traffic blocked'
            WHEN fail_cause IS NULL AND i.error_code IS NULL and status_id = 5 then 'No available engines'
            WHEN fail_cause is NULL and i.error_code IS NULL and status_id = 4 then 'Internal Error'
            WHEN fail_cause LIKE '%ip is in Form blacklist%' THEN 'IP is in Form Blacklist'
            WHEN i.error_code = 2009 THEN 'Order Expired'
            when status_id in (3, 4, 5) and i.engine_id is null then 'Unknown Reason'
            else 'not failed'
        END
        ELSE NULL
    END AS failed_cause
from orders.invoice i 
join clients.client c on c.id = i.client_id 
join lists.currency_list cl on cl.id = i.currency_id
join lists.invoice_status_list isl on isl.id = i.status_id 
where payer_id = {{payer_id_param}} and c."name" = {{client_name_param}}
UNION ALL
select 
    i.extra ->'payerInfo'->>'userID' as "Пользователь",
    i.id as "Номер ордера",
    c."name" as "Клиент",
    cl.system_name as "Валюта",
	wsl.system_name as "Статус",
    i.amount as "Сумма",
    (i.engine_ids IS NOT NULL) AS "Выданы реквизиты",
    i.created_at as "Дата создания",
    'payout' as "Тип ордера",
    
from orders.withdraw i
join clients.client c on c.id = i.client_id 
join lists.currency_list cl on cl.id = i.currency_id
join lists.withdraw_status_list wsl on wsl.id = i.status_id 
where i.extra ->'payerInfo'->>'userID' = {{payer_id_param}} and c."name" = {{client_name_param}}
ORDER BY "Дата создания" DESC;
